-- CREATE TABLE users
-- (
--   id SERIAL PRIMARY KEY,
--   firstname VARCHAR(30) NOT NULL,
--   lastname VARCHAR(30) NOT NULL,
--   email VARCHAR(30) UNIQUE NOT NULL,
--   password VARCHAR(250) NOT NULL,
--   "createdAt" TIMESTAMP Default Now()
-- );
-- CREATE TABLE entries
-- (
--   id SERIAL PRIMARY KEY,
--   user_id INT NOT NULL,
--   title VARCHAR(250) NOT NULL,
--   entry TEXT NOT NULL,
--   "createdAt" TIMESTAMP Default Now()
-- );
CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW()); CREATE TABLE IF NOT EXISTS entries (id SERIAL PRIMARY KEY, title VARCHAR(255) NOT NULL, image_url VARCHAR(1000), entry_note TEXT NOT NULL, user_id integer REFERENCES users (id), created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW());